# Use the official Node.js image as the base image
FROM node:22

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json (if exists)
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the Vue.js project files
COPY . .

# Command to start the Vue.js development server
CMD ["npm", "run", "dev"]
