# this docker compose file is used for local development ONLY, 
# hence the environment variables are set here.
# we deploy our application manually using Cloud Run (GCP).

version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.dev
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - IS_DEVELOPMENT=True
      - DATABASE_URL=postgresql://username:password@db:5432/music_composer
      - SECRET_KEY=9c77b62fd66e33db11d4e6e088d77e0d014151091fd40d85392a412a47bc4003
      - CORS_ORIGINS=http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
      - /app/backend/__pycache__/

  db:
    image: postgres
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=username
     - POSTGRES_DB=music_composer
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d music_composer"] 
      interval: 10s
      timeout: 5s
      retries: 4