# Dockerfile for Flask app
FROM python:3.9

# Set the working directory to /app (root of the project inside the container)
WORKDIR /app

# create a backend directory (this is needed so that the imports work correctly).
RUN mkdir /backend

# Copy all files into the container
COPY . /app/backend/

# Install dependencies requirements.txt
RUN pip install --no-cache-dir -r backend/requirements.txt

# for development
CMD ["python", "-m", "backend.src.run"]
