# Dockerfile for Flask app
FROM python:3.9

# Set the working directory to /app (root of the project inside the container)
WORKDIR /app

# create a backend directory (this is needed so that the imports work correctly).
RUN mkdir /backend

# Copy all files into the container
COPY . /app/backend/

# Install dependencies requirements.txt
RUN pip install --no-cache-dir -r backend/requirements.txt

# Set the entrypoint to run the app (only development or production)

# for development
CMD ["python", "-m", "backend.src.run"]

# for production
# CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "backend.src.run:app"] 
