name: Backend Workflow.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Install dependencies
      - name: Intstall dependencies
        run: pip install -r backend/requirements.txt

      # Run bandit & ruff
      - name: Run ruff
        run: ruff check backend/

      - name: run bandit
        run: bandit -c bandit.yaml -r backend/
      
  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Install dependencies
      - name: Intstall dependencies
        run: pip install -r backend/requirements.txt
      
      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose
        
      - name: Build and start services
        run: docker compose up -d --build backend db

      - name: Wait for services to be ready
        run: |
          until curl -s http://localhost:5000; do
            echo "Waiting for Flask app to be ready..."
            sleep 5
          done

      - name: Run tests
        run: |
          pip install pytest requests
          pytest backend/test/
      
      - name: Stop services
        run: docker compose down
      
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the Docker image
      - name: Build Docker image
        run: docker build -f ./backend/dockerfile.prod -t ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.run_number }} ./backend

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push the Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.run_number }}