name: Build and Push Docker Images

on:
  workflow_dispatch: # manual trigger.
  push:
    branches:
      - main  # Triggers workflow on push to 'main' branch
  pull_request:
    branches:
      - main  # Runs on PRs to 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and tag frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.run_number }} ./frontend

      - name: Push frontend image to Docker Hub
        run: docker push ${{secrets.DOCKER_USERNAME }}/frontend:${{ github.run_number }}

      - name: Build and tag backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.run_number }} ./backend

      - name: Push backend image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.run_number }}
